### 1. Lotto Project

In [1]:
import numpy as np
import pandas as pd

import scipy
from scipy import stats
import matplotlib.pyplot as plt

#### 1. Read csv file

In [2]:
lotto =pd.read_csv('./lotto1to961.csv')
print(lotto)
y=np.array([11,20,29,31,33,42])

     Num1  Num2  Num3  Num4  Num5  Num6
0      10    23    29    33    37    40
1       9    13    21    25    32    42
2      11    16    19    21    27    31
3      14    27    30    31    40    42
4      16    24    29    40    41    42
..    ...   ...   ...   ...   ...   ...
956     4    15    24    35    36    40
957     2     9    10    16    35    37
958     1    14    15    24    40    41
959     2    18    24    30    32    45
960    11    20    29    31    33    42

[961 rows x 6 columns]


#### 2. Change csv to array

In [3]:
# Delete last Winning number
FirstTo961=np.array(lotto)
print("FirstTo961 : ", FirstTo961)
FirstTo961=np.delete(FirstTo961,960,axis=0)
print("FirstTo961 : ", FirstTo961)

FirstTo961 :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 1 14 15 24 40 41]
 [ 2 18 24 30 32 45]
 [11 20 29 31 33 42]]
FirstTo961 :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 2  9 10 16 35 37]
 [ 1 14 15 24 40 41]
 [ 2 18 24 30 32 45]]


In [4]:
# Reshpae array
FirstTo961=FirstTo961.reshape(FirstTo961.shape[1], FirstTo961.shape[0], 1)
print("FirstTo961.shape : ", FirstTo961.shape)
print("y.shape", y.shape)

FirstTo961.shape :  (6, 960, 1)
y.shape (6,)


#### 3. Configuration Model

In [5]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

model=Sequential()
model.add(LSTM(7, input_shape=(960,1), activation='relu'))
model.add(Dense(4))
model.add(Dense(1))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 7)                 252       
_________________________________________________________________
dense (Dense)                (None, 4)                 32        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 5         
Total params: 289
Trainable params: 289
Non-trainable params: 0
_________________________________________________________________


#### 4. Training

In [6]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
model.fit(FirstTo961, y, epochs=100, batch_size=1)

Epoch 1/100
6/6 [==============================] - 2s 248ms/step - loss: nan - mse: nan   
Epoch 2/100
6/6 [==============================] - 1s 235ms/step - loss: nan - mse: nan
Epoch 3/100
6/6 [==============================] - 1s 241ms/step - loss: nan - mse: nan
Epoch 4/100
6/6 [==============================] - 1s 236ms/step - loss: nan - mse: nan
Epoch 5/100
6/6 [==============================] - 1s 205ms/step - loss: nan - mse: nan
Epoch 6/100
6/6 [==============================] - 1s 183ms/step - loss: nan - mse: nan
Epoch 7/100
6/6 [==============================] - 1s 156ms/step - loss: nan - mse: nan
Epoch 8/100
6/6 [==============================] - 1s 159ms/step - loss: nan - mse: nan
Epoch 9/100
6/6 [==============================] - 1s 154ms/step - loss: nan - mse: nan
Epoch 10/100
6/6 [==============================] - 1s 162ms/step - loss: nan - mse: nan
Epoch 11/100
6/6 [==============================] - 1s 204ms/step - loss: nan - mse: nan
Epoch 12/100
6/6 [=========

#### 5. Evaluation, Predict

In [7]:
lotto_predict=np.array([11,20,29,31,33,42])
lotto_predict=lotto_predict.reshape(1, 6, 1)
print("lotto_predict.shape : ", lotto_predict.shape)
y_predict=model.predict(lotto_predict)
print("Predict value : ", y_predict)

lotto_predict.shape :  (1, 6, 1)
Predict value :  [[nan]]
