### 2. MethodModel

#### 1. Data

In [1]:
import numpy as np
import pandas as pd

import scipy
from scipy import stats
import matplotlib.pyplot as plt

#### 1. Read csv file

In [2]:
lotto =pd.read_csv('./lotto1to961.csv')
print(lotto)
#y=np.array([11,20,29,31,33,42])
y=np.array([[11,20,29,31,33,42],[2,18, 24,30,32,45],[1,14,15,24,40,41],[2,9,10,16,35,37],[4,15,24,35,36,40],[10,11,20,21,25,41]])

     Num1  Num2  Num3  Num4  Num5  Num6
0      10    23    29    33    37    40
1       9    13    21    25    32    42
2      11    16    19    21    27    31
3      14    27    30    31    40    42
4      16    24    29    40    41    42
..    ...   ...   ...   ...   ...   ...
956     4    15    24    35    36    40
957     2     9    10    16    35    37
958     1    14    15    24    40    41
959     2    18    24    30    32    45
960    11    20    29    31    33    42

[961 rows x 6 columns]


#### 2. Change csv to array

In [3]:
# Delete last Winning number
FirstTo961=np.array(lotto)
print("FirstTo961 : ", FirstTo961)
FirstTo961=np.delete(FirstTo961,960,axis=0)
print("FirstTo961 : ", FirstTo961)

#check array shape
print("FirstTo961.shpae : ", FirstTo961.shape)
print("y.shape : ", y.shape)

FirstTo961 :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 1 14 15 24 40 41]
 [ 2 18 24 30 32 45]
 [11 20 29 31 33 42]]
FirstTo961 :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 2  9 10 16 35 37]
 [ 1 14 15 24 40 41]
 [ 2 18 24 30 32 45]]
FirstTo961.shpae :  (960, 6)
y.shape :  (6, 6)


In [4]:
#Check last 10
'''for i in range(949,len(FirstTo961)):            # 세로 크기
    for j in range(len(FirstTo961[i])):     # 가로 크기
        print(FirstTo961[i][j], end=' ')
    print()'''

"for i in range(949,len(FirstTo961)):            # 세로 크기\n    for j in range(len(FirstTo961[i])):     # 가로 크기\n        print(FirstTo961[i][j], end=' ')\n    print()"

#### 3. Model Configuration

In [5]:
from keras.models import Model
from keras.layers import Dense,Input

input1=Input(shape=(6,6))
dense1=Dense(100, activation='relu')(input1)
dense2=Dense(30)(dense1)
dense3=Dense(5)(dense2)
output1=Dense(1)(dense3)

model=Model(inputs=input1, outputs=output1)

#### 4. Training

In [6]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
#model.fit(FirstTo961, y, epochs=100, batch_size=1)
model.fit(FirstTo961, FirstTo961, epochs=100, batch_size=1)

Epoch 1/100
960/960 [==============================] - 2s 1ms/step - loss: 206.4558 - mse: 206.4558
Epoch 2/100
960/960 [==============================] - 1s 1ms/step - loss: 142.6846 - mse: 142.6846
Epoch 3/100
960/960 [==============================] - 1s 1ms/step - loss: 144.9606 - mse: 144.9606
Epoch 4/100
960/960 [==============================] - 1s 1ms/step - loss: 144.7321 - mse: 144.7321
Epoch 5/100
960/960 [==============================] - 1s 1ms/step - loss: 142.9574 - mse: 142.9574
Epoch 6/100
960/960 [==============================] - 1s 1ms/step - loss: 144.1360 - mse: 144.1360
Epoch 7/100
960/960 [==============================] - 1s 1ms/step - loss: 143.9153 - mse: 143.9153
Epoch 8/100
960/960 [==============================] - 1s 1ms/step - loss: 146.7318 - mse: 146.7318
Epoch 9/100
960/960 [==============================] - 1s 1ms/step - loss: 145.7553 - mse: 145.7553
Epoch 10/100
960/960 [==============================] - 1s 1ms/step - loss: 139.1823 - mse: 139.1823

#### 5. Evaluation, Predict

In [7]:
loss, mse=model.evaluate(FirstTo961, FirstTo961,batch_size=1)
print("mse : ", mse)
y_predict=model.predict(y)
print("predict : \n", y_predict)

960/960 [==============================] - 1s 1ms/step - loss: 143.8345 - mse: 143.8345
mse :  143.8345184326172
predict : 
 [[27.174734]
 [24.8144  ]
 [22.118622]
 [17.791767]
 [25.305304]
 [20.876549]]
