### 2. MethodModel

#### 1. Data

In [1]:
import numpy as np
import pandas as pd

import scipy
from scipy import stats
import matplotlib.pyplot as plt

#### 1. Read csv file

In [2]:
lotto =pd.read_csv('./LuckData.csv')
print(lotto)
#962
N=np.array([1,18,28,31,34,43])
y=np.array([[1,18,28,31,34,43],[11,20,29,31,33,42],[2,18, 24,30,32,45],[1,14,15,24,40,41],[2,9,10,16,35,37],[4,15,24,35,36,40]])

     Num1  Num2  Num3  Num4  Num5  Num6
0      10    23    29    33    37    40
1       9    13    21    25    32    42
2      11    16    19    21    27    31
3      14    27    30    31    40    42
4      16    24    29    40    41    42
..    ...   ...   ...   ...   ...   ...
956     4    15    24    35    36    40
957     2     9    10    16    35    37
958     1    14    15    24    40    41
959     2    18    24    30    32    45
960    11    20    29    31    33    42

[961 rows x 6 columns]


#### 2. Change csv to array

In [3]:
# Delete last Winning number
FirstToEnd=np.array(lotto)
print("FirstToEnd : ", FirstToEnd)
FirstToEnd=np.vstack([FirstToEnd,N])
print("FirstToEnd+N : ", FirstToEnd)
#check array shape
print("FirstToEnd.shpae : ", FirstToEnd.shape)
print("y.shape : ", y.shape)

head={'no':['num1', 'num2', 'num3', 'num4' ,'num5', 'num6']}
save=pd.DataFrame(FirstToEnd)
save.to_csv("LuckData.csv", header=head, index=False)

FirstToEnd :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 1 14 15 24 40 41]
 [ 2 18 24 30 32 45]
 [11 20 29 31 33 42]]
FirstToEnd+N :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 2 18 24 30 32 45]
 [11 20 29 31 33 42]
 [ 1 18 28 31 34 43]]
FirstToEnd.shpae :  (962, 6)
y.shape :  (6, 6)
