### 2. MethodModel

#### 1. Data

In [1]:
import numpy as np
import pandas as pd

import scipy
from scipy import stats
import matplotlib.pyplot as plt

#### 1. Read csv file

In [2]:
lotto =pd.read_csv('./LuckData.csv')
print(lotto)
#962
N=np.array([1,18,28,31,34,43])
y=np.array([[1,18,28,31,34,43],[11,20,29,31,33,42],[2,18, 24,30,32,45],[1,14,15,24,40,41],[2,9,10,16,35,37],[4,15,24,35,36,40]])

      0   1   2   3   4   5
0    10  23  29  33  37  40
1     9  13  21  25  32  42
2    11  16  19  21  27  31
3    14  27  30  31  40  42
4    16  24  29  40  41  42
..   ..  ..  ..  ..  ..  ..
957   2   9  10  16  35  37
958   1  14  15  24  40  41
959   2  18  24  30  32  45
960  11  20  29  31  33  42
961   1  18  28  31  34  43

[962 rows x 6 columns]


#### 2. Change csv to array

In [3]:
# Delete last Winning number
FirstToEnd=np.array(lotto)
print("FirstToEnd : ", FirstToEnd)

#check array shape
print("FirstToEnd.shpae : ", FirstToEnd.shape)
print("y.shape : ", y.shape)

FirstToEnd :  [[10 23 29 33 37 40]
 [ 9 13 21 25 32 42]
 [11 16 19 21 27 31]
 ...
 [ 2 18 24 30 32 45]
 [11 20 29 31 33 42]
 [ 1 18 28 31 34 43]]
FirstToEnd.shpae :  (962, 6)
y.shape :  (6, 6)


#### 3. Model Configuration

In [4]:
from keras.models import Model
from keras.layers import Dense,Input

'''
input1=Input(shape=(6,6))
dense1=Dense(100, activation='relu')(input1)
dense2=Dense(30)(dense1)
dense3=Dense(5)(dense2)
output1=Dense(1)(dense3)
'''

input1=Input(shape=(6,6))
dense1=Dense(45, activation='relu')(input1)
dense2=Dense(44)(dense1)
dense3=Dense(43)(dense2)
dense4=Dense(42)(dense3)
dense5=Dense(41)(dense4)
dense6=Dense(5)(dense5)
output1=Dense(1)(dense6)

model=Model(inputs=input1, outputs=output1)

#### 4. Training

In [5]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])
#model.fit(FirstTo961, y, epochs=100, batch_size=1)
model.fit(FirstToEnd, FirstToEnd, epochs=100, batch_size=1)

Epoch 1/100
962/962 [==============================] - 2s 2ms/step - loss: 149.7937 - mse: 149.7937
Epoch 2/100
962/962 [==============================] - 1s 1ms/step - loss: 145.1583 - mse: 145.1583
Epoch 3/100
962/962 [==============================] - 1s 1ms/step - loss: 143.2605 - mse: 143.2605
Epoch 4/100
962/962 [==============================] - 1s 1ms/step - loss: 144.1341 - mse: 144.1341
Epoch 5/100
962/962 [==============================] - 1s 1ms/step - loss: 141.3203 - mse: 141.3203
Epoch 6/100
962/962 [==============================] - 1s 1ms/step - loss: 144.6707 - mse: 144.6707
Epoch 7/100
962/962 [==============================] - 1s 1ms/step - loss: 144.1887 - mse: 144.1887
Epoch 8/100
962/962 [==============================] - 1s 1ms/step - loss: 143.1008 - mse: 143.1008
Epoch 9/100
962/962 [==============================] - 1s 1ms/step - loss: 145.0304 - mse: 145.0304
Epoch 10/100
962/962 [==============================] - 1s 1ms/step - loss: 142.9397 - mse: 142.9397

#### 5. Evaluation, Predict

In [6]:
loss, mse=model.evaluate(FirstToEnd, FirstToEnd,batch_size=1)
print("mse : ", mse)
y_predict=model.predict(y)
print("predict : \n", y_predict)

962/962 [==============================] - 1s 1ms/step - loss: 143.6338 - mse: 143.6338A: 0s - loss: 143.1624 - mse: 143.
mse :  143.63381958007812
predict : 
 [[25.819798]
 [27.654255]
 [25.15266 ]
 [22.48904 ]
 [18.158585]
 [25.654303]]
